[package]
name = "deployment-copy"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "decopy"
path = "src/main.rs"

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
crossterm = "0.26.0"
fs_extra = "1.3.0"
strip-ansi-escapes = "0.1.1"
