name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Tag And Release Rust binary
        uses: xhaiker/rust-release.action@v1.0.2
        with:
          rust_target: x86_64-pc-windows-gnu
