name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Rust Release binary
        uses: rust-build/rust-build.action@v1.4.2
